version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    container_name: onepiece-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
    container_name: onepiece-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
    command: ["./main"]

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge

